export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const REMOVE_ACTIVITY = "REMOVE_ACTIVITY";
export const PERFORM_ACTIVITY = "PERFORM_ACTIVITY";
export const SET_ACTIVITY = "SET_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
